### ISSUE TITLE
Allow use of add_help argument in ArgumentParser creation

### ISSUE THREAD

**Issue by chlige** [trevorld/r-argparse#27]
If the add_help argument is added in the ArgumentParser creation statement it is not properly translated into a Python boolean.  Currently it is converted into a string.  The following patch would properly convert an R boolean into a python boolean.  I grant the main developer a non-exclusive
unlimited license for the code in this patch.

[argparse-patch.txt](https://github.com/trevorld/r-argparse/files/2669422/argparse-patch.txt)

**Comment by trevorld** [comment]
@chlige Thanks for the bug report (and patch)!  Should be fixed now in the development version.  Decided this was a good point for me to re-factor the ``convert_..._to_arguments`` code a bit to hopefully fix more of these conversion bugs so I didn't directly use your patch.
