### ISSUE TITLE
Support 'set_defaults()'

### ISSUE THREAD

**Issue by oliverbothe** [trevorld/r-argparse#43]
This is a noob question and I unfortunately do not have a minimal working example. 

I struggle with accessing the sub-command from a subparser. That is taking your vignette as an example

```
> parser$print_help()
usage: PROG [-h] [--foo] {a,b} ...

positional arguments:
  {a,b}       sub-command help
    a         a help
    b         b help
   
```
I would like to access whether the user wanted sub-command `a` or sub-command `b`. Or rather I would like to connect functions directly to `a` and `b`. If I understand the docs for Python's `argparse` correctly that is possible with `set_defaults` (compare [here](https://docs.python.org/3/library/argparse.html#sub-commands)). 

Would it be possible to include something like this in your R-package or do I simply miss that it is already included? 

Sorry, if this is the wrong place to ask this.

**Comment by trevorld** [comment]
Currently `{argparse}` is a wrapper around Python's `argparse` and `{argparse}` currently doesn't support passing functions back and forth so even if we added support for `set_defaults()` (which would work with non-function defaults) that particular approach wouldn't currently work.  

An alternative approach if using the `dest` argument of `add_subparsers()` would be to use a switch statement on the subparser name e.g.:

```r
switch(args$subparser_name,
            foo = foo_fn(args),
            bar = bar_fn(args),
            stop("Unknown subparser")
```

**Comment by trevorld** [comment]
On second though although we don't currently support passing functions back and forth you could pass the function **name** and then in R simply call `get()` on the name to get the function e.g. do something like:

```r
get(args$func)(args)
```

instead of the Pythonic approach you linked to:

```python
args.func(args)
```
