### ISSUE TITLE
question: should I use argparse instead of optparse going forward

### ISSUE THREAD

**Issue by ssh352** [trevorld/r-argparse#50]
optparse in python is deprecated.

Thanks!

**Comment by trevorld** [comment]
* I don't have any plans to end support for `{optparse}` which really is quite sufficient for many use cases.
* `{argparse}` currently has a Python run-time dependency while `{optparse}` doesn't have any such run-time dependency.
* `{argparse}` does support some features which `{optparse}` is unlikely to support.
* I personally usually use `{optparse}` unless I really want a feature that only `{argparse}` provides (such as sub-parsers) in which case I'll use it instead.
